### ISSUE TITLE
Small collection of feedback

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beakerbrowser.com#13]
- max: "Beaker is a new browser and protocol" -- protocol seems weird
- brian
   - i would make it ‘browse / build / experiment'
   - you could change ‘experiment’ to ‘borrow’ too? i mean it’s slightly less exactly what’s happening but dat illeteration
   - border radius looks different on the 3 panels and the buttons
 - jhand
   - "its not clear to me reading the site that you can browser normal sites too"
   - "opacity animation on the video is a bit much for me (its seems like that or the play button affecting the font render on "watch the demo")"
 - me:
    - we should indicate that it's in an unfinished state (pre alpha)
    - I think I want to revisit our intro copy lol
 - john
    - http://storage.j0.hn/suggestion-1.gif
    - http://storage.j0.hn/suggestion-2.gif
    - I'd also get rid of the borders going around those 3 marketing points and just do in-between separators
    - also, I'd bump your button padding from .4 .7 to .5 .8

**Comment by taravancil** [comment]
This was all very helpful. Thanks everyone 😊 

@pfrazee I'm starting to think there will never be a time that we won't want to revisit the intro copy lol

**Comment by pfrazee** [comment]
I think we're good on this
