### ISSUE TITLE
Dat over TLS ( dat://beakerbrowser.com )

### ISSUE THREAD

**Issue by dcposch** [beakerbrowser/beakerbrowser.com#32]
`dat://beakerbrowser.com` was the first URL it tried after reading about the Dat over HTTPS feature, but it doesn't resolve yet :)

by comparison, `hostless.website` loads over HTTPS now. it's super cool:

![image](https://cloud.githubusercontent.com/assets/169280/24836286/08f1923c-1ccd-11e7-9206-f30f8be6f9a6.png)

![image](https://cloud.githubusercontent.com/assets/169280/24836293/1ca2cf94-1ccd-11e7-983a-f6d48faa85b6.png)

**Comment by pfrazee** [comment]
Yeah we need to convert it to a dat!

**Comment by pfrazee** [comment]
Done!
