### ISSUE TITLE
Certificate expired for https://beakerbrowser.com

### ISSUE THREAD

**Issue by aribn** [beakerbrowser/beakerbrowser.com#36]
https://beakerbrowser.com currently returns an error due to an expired certificate. 

<img width="465" alt="screen shot 2017-05-01 at 9 45 29 pm" src="https://cloud.githubusercontent.com/assets/34577/25604355/a7a4009e-2eb7-11e7-881d-63156075bafc.png">

**Comment by pfrazee** [comment]
Thanks for the heads up! My lets encrypt script was running but I didnt have nginx run reload automatically, so the new cert wasn't being used. Fixed now.
