### ISSUE TITLE
Homepage mobile layout broken

### ISSUE THREAD

**Issue by jesusgollonet** [beakerbrowser/beakerbrowser.com#63]
Hey, I'm not sure if this is the same as #51, but the layout is seriously broken on the homepage for mobile.

Have pulled and tried to compile the site locally but for some reason sass will not compile. If I figure it out i'll make a PR but i think it has to do with `flex-container: row` in `.hero__links`. If I set it to `column` the layout looks correct on both mobile and desktop (haven't done a lot of browser testing yet though).

![screen shot 2017-08-22 at 12 49 27](https://user-images.githubusercontent.com/31100/29562273-e68b0f44-8738-11e7-8f96-698093326e49.png)

**Comment by pfrazee** [comment]
Hey thanks, we actually found this ourselves last night. We'll look into it asap!

**Comment by taravancil** [comment]
Thanks! This is fixed in master and will be launched soon
