### ISSUE TITLE
Feed(s)?

### ISSUE THREAD

**Issue by ghost** [beakerbrowser/beakerbrowser.com#64]
- rss
- atom
- activitystreams
- jsonfeed

or will you tell to just follow on twitter?

**Comment by pfrazee** [comment]
Currently in progress: https://github.com/beakerbrowser/beaker-profiles-api

See the functions for 'broadcasts'

**Comment by pfrazee** [comment]
Oh hah, this is on the beakerbrowser.com repo.

Yeah we just have twitter for now. @BeakerBrowser
