### ISSUE TITLE
Should it work over VPN?

### ISSUE THREAD

**Issue by digitaldonkey** [beakerbrowser/beakerbrowser.com#74]
![image](https://user-images.githubusercontent.com/444718/40888536-e0db6ac0-6758-11e8-86b6-3e9ae0ffb442.png)

**Comment by pfrazee** [comment]
I think we have some kind of bug with DNS, because it temperamentally fails like this. Not sure about the VPN having an effect on this.

**Comment by digitaldonkey** [comment]
Seemed to be DNS. Today it worked.
