### ISSUE TITLE
Incorrect url header jump links ./docs/all/

### ISSUE THREAD

**Issue by tfolbrecht** [beakerbrowser/beakerbrowser.com#82]
[https://beakerbrowser.com/docs/all/](https://beakerbrowser.com/docs/all/)

[### Tour](https://beakerbrowser.com/docs/tour/)
- [Browsing with Beaker](https://beakerbrowser.com/docs/all/#browsing-with-beaker)
- [View Source](https://beakerbrowser.com/docs/all/#view-source)
- [One-click publishing](https://beakerbrowser.com/docs/all/#one-click-publishing)
- [Built-in editor](https://beakerbrowser.com/docs/all/#beakers-built-in-editor)
- ["Forking" or copying a website](https://beakerbrowser.com/docs/all/#forking-or-copying-a-website)
- [Live reloading](https://beakerbrowser.com/docs/all/#live-reloading)

should be

[### Tour](https://beakerbrowser.com/docs/tour/)
- [Browsing with Beaker](https://beakerbrowser.com/docs/tour/#browsing-with-beaker)
- [View Source](https://beakerbrowser.com/docs/tour/#view-source)
- [One-click publishing](https://beakerbrowser.com/docs/tour/#one-click-publishing)
- [Built-in editor](https://beakerbrowser.com/docs/tour/#beakers-built-in-editor)
- ["Forking" or copying a website](https://beakerbrowser.com/docs/tour/#forking-or-copying-a-website)
- [Live reloading](https://beakerbrowser.com/docs/tour/#live-reloading)

**Comment by tfolbrecht** [comment]
It's because the articles haven't been broken into sectioned .md files as per _docs/all/index.md

Saw there were links to what would be sections that make _docs/all/index.md work commented out (_docs/tour/index.md, _docs/faq/index.md) so I assume its on a todo list somewhere! Let me know if I can help 😃

beakerbrowser.com/blob/master/_docs/all/index.md

**Comment by pfrazee** [comment]
Okay figured this out and pushing a fix. Thanks!
