### ISSUE TITLE
It would be useful to provide more info for opts.links 

### ISSUE THREAD

**Issue by Gozala** [beakerbrowser/beakerbrowser.com#85]
<img width="539" alt="screen shot 2018-08-24 at 10 09 36 am" src="https://user-images.githubusercontent.com/21236/44597867-f5bb9380-a785-11e8-9a09-0255276faf72.png">

[fork](https://beakerbrowser.com/docs/apis/dat#fork), [create](https://beakerbrowser.com/docs/apis/dat#create), [configure](https://beakerbrowser.com/docs/apis/dat#configure) all mention to `opts.links` but actual info about the shape of the links is in [`dat.json`](https://beakerbrowser.com/docs/apis/manifest.html#links) docs. I'd recommend adding a link so it's easier for newcomers to figure out.

**Comment by pfrazee** [comment]
Good recommendation, thanks
