### ISSUE TITLE
Incorrect font displayed in "How Beaker Works" SVG

### ISSUE THREAD

**Issue by yunyu** [beakerbrowser/beakerbrowser.com#88]
It looks like the file [references Inter UI](https://raw.githubusercontent.com/beakerbrowser/beakerbrowser.com/master/img/how-it-works/url-bar.svg), but it will just display a fallback font when displayed on a computer without that font installed. The solution would be to render the font as an outline.

Here is what it looks like on my computer:

![](https://vgy.me/WnFPFs.png)

**Comment by pfrazee** [comment]
Thanks for filing. I'll check into it.

**Comment by pfrazee** [comment]
Fixed! Thanks
